### ISSUE TITLE
/run/current-system/sw/bin/wgnord: line 16: /var/lib/wgnord/credentials.json: No such file or directory jq: error: Could not open file /var/lib/wgnord/credentials.json: No such file or directory

### ISSUE THREAD

**Issue by Merulox** [phirecc/wgnord#2]
> sudo wgnord l e9*****
/run/current-system/sw/bin/wgnord: line 16: /var/lib/wgnord/credentials.json: No such file or directory
jq: error: Could not open file /var/lib/wgnord/credentials.json: No such file or directory
>

Running on NixOS

Thank you for your time!

**Comment by phirecc** [comment]
(edit: I misread the error in my previous reply)
Hi,
I think the error is due to the `/var/lib/wgnord` directory not existing. Did you follow the installation steps in the readme? It should be created on installation.

**Comment by Merulox** [comment]
> (edit: I misread the error in my previous reply) Hi, I think the error is due to the `/var/lib/wgnord` directory not existing. Did you follow the installation steps in the readme? It should be created on installation.

Thank you, it worked fine after I manually created the directories it asked me to. I'd installed it through nixpkgs without doing anything else.

**Comment by phirecc** [comment]
Oh wow, I didn't know someone made a nix package for wgnord. That's cool :)

I think the problem lies in the nix install script. I believe it would be better if the `postPatch` section just changed the definition of `conf_dir` to `$out/share/` here:
https://github.com/NixOS/nixpkgs/blob/c96b386640b0c11bbb6d878d86ec39629ab92997/pkgs/applications/networking/wgnord/default.nix#L25

So something like this:
```
postPatch = ''
    substituteInPlace wgnord \
      --replace 'conf_dir=/var/lib/wgnord' "conf_dir=$out/share"
  '';
```
The linked code only changes the path of `countries.txt` and `countries_iso31662.txt`, but `credentials.json`, `coords.json` and `template.conf` are still attempted to be read from `/var/lib/wgnord`. It also appears not to install `template.conf` at all?

I'm not too familiar with nix though, maybe you could make an issue?
Thanks

**Comment by getreu** [comment]
I needed to create manually:

    mkdir /etc/wireguard
    mkdir /var/lib/wgnord

to make this work. This should be part of the installation process!(?) Please reopen this issue.

**Comment by phirecc** [comment]
What distribution are you using? On arch `/etc/wireguard` is created by the `wireguard-tools` dependency.
And `/var/lib/wgnord` is should be created by the `install` commands in the manual installation instructions in the readme.

**Comment by getreu** [comment]
I am using Nixos. I thought I was in the `nixpkgs` repository and talking to the Nix package maintainer. I did not notice that i am posting upstream. Sorry.

**Comment by phirecc** [comment]
No problem :)
