### ISSUE TITLE
Support: Manually enable ipv6

### ISSUE THREAD

**Issue by Silverdev2482** [phirecc/wgnord#4]
I would imagine I need to specify an address, and search domain for enabling ipv6 via NordVPN, is that correct? If so what should they be set to to get ipv6 working? If not what is the correct process?

**Comment by Bundy01** [comment]
Hi,
NordVpn uses only IPV6 servers in OpenVPN, 2 in UDP and 2 in TCP.
At present, there are no Wireguard-compatible servers :(

**Comment by Silverdev2482** [comment]
Well this sounds like user error.

**Comment by Silverdev2482** [comment]
No, apparently it supports it, this [(fork? or just very similar tool)](https://github.com/n-thumann/wg-nord) appears to support it but it isn't packaged on NixOS, although it may not be that hard to package.

**Comment by phirecc** [comment]
The project you linked to says only 2 of their servers support IPv6.
As far as I see the project's IPv6 support is limited to being able to tell whether a server supports IPv6 and preventing you from setting an IPv6 DNS or AllowedIP if it doesn't. These checks are out of scope for `wgnord` because it just does string replacements on a `template.conf` you give it.
Unlike `wgnord`, it uses the VPN server's hostname as opposed to its IPv4 in the endpoint field. This will let your OS choose whether to use IPv4 or IPv6 when connecting to it.

When #5 is implemented you'll be able to choose to connect to one of those 2 servers specifically and there could be a flag to choose using hostnames or prefer IPv6.
